#+DATE: 2019/02/19 12:29:08

* A Package to Render Org to Hexo's Markdown

Just for users who are perflexed by that Hexo can't render Org directly.

** Update

Just reconstruct it to make it better.

** Installation

*** Manual Installation

At this time, it still be not uploaded Melpa, and you can install it manually.

#+BEGIN_SRC sh
git clone https://github.com/loveminimal/org2md.git
#+END_SRC

and, add the following contents to your init.el:

#+BEGIN_SRC elisp
  (add-to-list 'load-path "<path where org2md is installed>")
  (require 'org2md)
#+END_SRC

*** Melpa

You can install =org2md= using melpa later, like this:

#+BEGIN_SRC elisp
  M-x package-install org2md
#+END_SRC

and if you use =use-package= manage your configurations, this way is okay:

#+BEGIN_SRC elisp
  (use-package org2md
    :ensure t)
#+END_SRC

** Usage

This package is used to render a =.org= file to a =.md= file which can be rendered by HEXO.

It offers two useful functions, and you must execute them in order, like this:

*** org2md-insert-date

It will be insert a time string like this:

#+BEGIN_EXAMPLE
  #+DATE: 2019/02/19 12:29:08
#+END_EXAMPLE

It must be executed before =org2md-export-md=. 

*** org2md-export-md

It must be executed after =org2md-insert-date=. 

It will be insert a front-matter in a generated =.md= file, like this:

#+BEGIN_EXAMPLE
  ---
  title: get things done  
  date: 2018/06/09 12:46:29
  updated: 2019/02/10 12:46:52
  ---
  ...
  ...
#+END_EXAMPLE

*** Summary

1. Make sure that in a =.org= buffer, such as =xx/_orgs/hello-world.org=, then
2. execute =org2md-insert-date= , like =M-x org2md-insert-date=, then
3. execute =org2md-export-md=

Now, here will be a =.md= file, such as =xx/_posts/hello-world.md=.

If you update the =.org= file again, just run =org2md-export-md= to update the relative =.md= file.

#+BEGIN_QUOTE
  NOTE: =org2md-insert-date= must be executed before =org2md-export-md=.
#+END_QUOTE
